### ISSUE TITLE
Requests hang when querying empty files

### ISSUE THREAD

**Issue by fbonecco-cribl** [whargrove/qlog#4] opened 2024-02-16 14:17 UTC
Hi @whargrove this is Franco from Cribl, again :).

Please see the behavior when querying empty files.

- Request issued is:
`http://localhost:8080/queryLog?relativePath=empty`
- Process goes up to +250% in CPU utilization.
![image](https://github.com/whargrove/qlog/assets/77752546/95f6c233-0843-49ed-8659-7d9580b3272e)
- Request doesn't complete:
`franco@franco:~$ curl -v  "http://localhost:8080/queryLog?relativePath=empty"
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /queryLog?relativePath=empty HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> 
`
Environment:
![image](https://github.com/whargrove/qlog/assets/77752546/8012a10e-128b-496e-bd53-5dc7992aa785)

**Comment by whargrove** [comment] 2024-02-17 18:30
Hi @fbonecco-cribl ! Thanks for checking out the project. Yes, this is unexpected behavior. I've merged a PR that fixes the root cause.

**Closed as completed by whargrove** 2024-02-17 18:30 UTC
Labels: bug
